spring:
  application:
    name: invoice-service
  datasource:
    url: jdbc:mysql://localhost:3306/invoice_db
    username: root
    password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 0

